[2025-08-28T06:10:58.168+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T06:10:58.219+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: contoh_taskgroup_api_santai.selesai manual__2025-08-28T06:10:33.883027+00:00 [queued]>
[2025-08-28T06:10:58.238+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: contoh_taskgroup_api_santai.selesai manual__2025-08-28T06:10:33.883027+00:00 [queued]>
[2025-08-28T06:10:58.239+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T06:10:58.263+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): selesai> on 2025-08-28 06:10:33.883027+00:00
[2025-08-28T06:10:58.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=923) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-28T06:10:58.290+0000] {standard_task_runner.py:63} INFO - Started process 925 to run task
[2025-08-28T06:10:58.291+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'contoh_taskgroup_api_santai', 'selesai', 'manual__2025-08-28T06:10:33.883027+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpv7c50ilr']
[2025-08-28T06:10:58.296+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask selesai
[2025-08-28T06:10:58.417+0000] {task_command.py:426} INFO - Running <TaskInstance: contoh_taskgroup_api_santai.selesai manual__2025-08-28T06:10:33.883027+00:00 [running]> on host 97ae95ca845c
[2025-08-28T06:10:58.606+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='contoh_taskgroup_api_santai' AIRFLOW_CTX_TASK_ID='selesai' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T06:10:33.883027+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T06:10:33.883027+00:00'
[2025-08-28T06:10:58.611+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T06:10:58.612+0000] {python.py:237} INFO - Done. Returned value was: <function info at 0x7a33bffaa480>
[2025-08-28T06:10:58.614+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T06:10:58.630+0000] {xcom.py:675} ERROR - Object of type function is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-08-28T06:10:58.634+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'function'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
[2025-08-28T06:10:58.655+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=contoh_taskgroup_api_santai, task_id=selesai, run_id=manual__2025-08-28T06:10:33.883027+00:00, execution_date=20250828T061033, start_date=20250828T061058, end_date=20250828T061058
[2025-08-28T06:10:58.685+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task selesai (Object of type function is not JSON serializable; 925)
[2025-08-28T06:10:58.748+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T06:10:58.789+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T06:10:58.793+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
